version: '3.1'

services:

  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: heroes
      POSTGRES_PASSWORD: heroes
      POSTGRES_DB: heroes

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db